public_repo_path=imgly/starterkit-postcard-editor-android
public_repo_description=Postcard Editor starter kit that is built on top of the Creative Editor SDK.
gradle_project_name=starter-kit-postcard
app_name=Postcard Editor
package_suffix=postcard
